export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface ApiEndpoint {
  id: string;
  title: string;
  method: HttpMethod;
  href: string;
  path: string;
  description: string;
  longDescription?: string;
  headers?: { key: string; value: string; required: boolean }[];
  requestBody?: { field: string; type: string; required: boolean; description: string }[];
  responseBody?: { field: string; type: string; description: string }[];
  exampleRequest?: string;
  exampleResponse?: string;
}

export interface ApiGroup {
  id: string;
  title: string;
  endpoints: ApiEndpoint[];
}

export const apiGroups: ApiGroup[] = [
  {
    id: "packages",
    title: "Packages",
    endpoints: [
      {
        id: "search-packages",
        title: "Search Packages",
        method: "GET",
        href: "/api/search-packages",
        path: "/v1/packages?q={term}",
        description: "Search for packages published in the official Sotlas registry.",
        longDescription:
          "Returns the list of packages matching the search term, ranked by relevance. This endpoint is public and requires no authentication.",
        headers: [{ key: "Accept", value: "application/json", required: true }],
        responseBody: [
          { field: "results", type: "array", description: "List of matching packages." },
          { field: "results[].name", type: "string", description: "Package name." },
          { field: "results[].latest", type: "string", description: "Most recent stable version." },
          { field: "total", type: "number", description: "Total number of results." },
        ],
        exampleResponse: `{
  "results": [
    {
      "name": "sot-http",
      "latest": "1.2.0",
      "description": "HTTP client and server library for Sotlas"
    }
  ],
  "total": 1
}`,
      },
      {
        id: "package-details",
        title: "Package Details",
        method: "GET",
        href: "/api/package-details",
        path: "/v1/packages/{name}",
        description: "Retrieve metadata, versions, and supported targets for a package.",
        longDescription:
          "Provides the description, license, source repository, all published versions, and supported compilation targets for the given package.",
        headers: [{ key: "Accept", value: "application/json", required: true }],
        responseBody: [
          { field: "name", type: "string", description: "Package name." },
          { field: "license", type: "string", description: "Declared manifest license." },
          { field: "versions", type: "array", description: "Published versions, ordered from newest to oldest." },
          { field: "targets", type: "array", description: "Supported compilation targets." },
        ],
        exampleResponse: `{
  "name": "sot-http",
  "license": "MIT",
  "versions": ["1.2.0", "1.1.3", "1.0.0"],
  "targets": ["x86_64-linux", "aarch64-macos", "riscv64-none-elf"]
}`,
      },
      {
        id: "publish-package",
        title: "Publish Package",
        method: "POST",
        href: "/api/publish-package",
        path: "/v1/packages",
        description: "Publish a new package release to the registry.",
        longDescription:
          "Uploads the compressed package archive along with cryptographic signatures generated by the CLI. Published versions are immutable.",
        headers: [
          { key: "Content-Type", value: "application/json", required: true },
          { key: "Authorization", value: "Bearer {token}", required: true },
        ],
        requestBody: [
          { field: "name", type: "string", required: true, description: "Package name." },
          { field: "version", type: "string", required: true, description: "Semantic version string." },
          { field: "archive", type: "string", required: true, description: "Base64-encoded package archive." },
          { field: "signature", type: "string", required: true, description: "Signature generated by sot pkg sign." },
        ],
        responseBody: [
          { field: "name", type: "string", description: "Published package name." },
          { field: "version", type: "string", description: "Published version." },
          { field: "published_at", type: "string", description: "Publication timestamp." },
        ],
        exampleRequest: `{
  "name": "sot-http",
  "version": "1.2.0",
  "archive": "UEsDBBQAAAAIAA...",
  "signature": "ed25519:9f2c..."
}`,
        exampleResponse: `{
  "name": "sot-http",
  "version": "1.2.0",
  "published_at": "2026-09-02T14:05:00Z"
}`,
      },
      {
        id: "yank-version",
        title: "Yank Version",
        method: "DELETE",
        href: "/api/yank-version",
        path: "/v1/packages/{name}/{version}",
        description: "Marks a package version as yanked without removing it from existing builds.",
        longDescription:
          "A yanked version remains accessible to existing lockfiles but is omitted from new resolution queries. Use this when discovering a critical security flaw.",
        headers: [{ key: "Authorization", value: "Bearer {token}", required: true }],
        requestBody: [
          { field: "reason", type: "string", required: false, description: "Reason displayed to users of this version." },
        ],
        responseBody: [
          { field: "yanked", type: "boolean", description: "Indicates whether the version was yanked." },
          { field: "message", type: "string", description: "Status confirmation message." },
        ],
        exampleResponse: `{
  "yanked": true,
  "message": "Version 1.1.3 yanked from registry"
}`,
      },
    ],
  },
  {
    id: "toolchain",
    title: "Toolchain Releases",
    endpoints: [
      {
        id: "list-releases",
        title: "List Releases",
        method: "GET",
        href: "/api/list-releases",
        path: "/v1/toolchain/releases",
        description: "List toolchain versions available for download.",
        longDescription:
          "Used by installers and CI/CD pipelines to discover stable, beta, and nightly releases of the compiler.",
        headers: [{ key: "Accept", value: "application/json", required: true }],
        responseBody: [
          { field: "releases", type: "array", description: "Available releases." },
          { field: "releases[].version", type: "string", description: "Version number string." },
          { field: "releases[].channel", type: "string", description: "Release channel: stable, beta, or nightly." },
          { field: "releases[].platforms", type: "array", description: "Supported platform binaries." },
        ],
        exampleResponse: `{
  "releases": [
    {
      "version": "0.5.1",
      "channel": "stable",
      "platforms": ["x86_64-linux", "aarch64-macos", "x86_64-windows"]
    }
  ]
}`,
      },
      {
        id: "check-updates",
        title: "Check for Updates",
        method: "GET",
        href: "/api/check-updates",
        path: "/v1/toolchain/check?version={current}",
        description: "Checks whether a newer version of the toolchain is available.",
        headers: [{ key: "Accept", value: "application/json", required: true }],
        responseBody: [
          { field: "update_available", type: "boolean", description: "Indicates if an update is available." },
          { field: "latest", type: "string", description: "Latest available version." },
          { field: "notes_url", type: "string", description: "URL to release notes." },
        ],
        exampleResponse: `{
  "update_available": true,
  "latest": "0.5.1",
  "notes_url": "/changelog"
}`,
      },
    ],
  },
  {
    id: "account",
    title: "Publishing Account",
    endpoints: [
      {
        id: "create-token",
        title: "Create Token",
        method: "POST",
        href: "/api/create-token",
        path: "/v1/tokens",
        description: "Generate a publication token linked to your account.",
        longDescription:
          "Tokens are consumed by sot pkg publish and automated CI pipelines. The raw token secret is shown only once upon creation.",
        headers: [
          { key: "Content-Type", value: "application/json", required: true },
          { key: "Authorization", value: "Bearer {token}", required: true },
        ],
        requestBody: [
          { field: "name", type: "string", required: true, description: "Name identifying the token." },
          { field: "scopes", type: "array", required: true, description: "Granted permissions (e.g. publish, yank)." },
        ],
        responseBody: [
          { field: "token", type: "string", description: "Token value, displayed only once." },
          { field: "scopes", type: "array", description: "Granted permission scopes." },
          { field: "created_at", type: "string", description: "Creation timestamp." },
        ],
        exampleRequest: `{
  "name": "ci-github",
  "scopes": ["publish"]
}`,
        exampleResponse: `{
  "token": "sot_pat_9f2c4b...",
  "scopes": ["publish"],
  "created_at": "2026-09-02T14:05:00Z"
}`,
      },
      {
        id: "revoke-token",
        title: "Revoke Token",
        method: "DELETE",
        href: "/api/revoke-token",
        path: "/v1/tokens/{id}",
        description: "Immediately revoke an active publication token.",
        headers: [{ key: "Authorization", value: "Bearer {token}", required: true }],
        responseBody: [
          { field: "revoked", type: "boolean", description: "Indicates whether the token was revoked." },
          { field: "message", type: "string", description: "Confirmation message." },
        ],
        exampleResponse: `{
  "revoked": true,
  "message": "Token revoked successfully"
}`,
      },
    ],
  },
];

const API_SLUG_ALIASES: Record<string, string> = {
  "buscar-pacotes": "search-packages",
  "detalhes-do-pacote": "package-details",
  "publicar-pacote": "publish-package",
  "remover-versao": "yank-version",
  "listar-releases": "list-releases",
  "verificar-atualizacao": "check-updates",
  "criar-token": "create-token",
  "revogar-token": "revoke-token",
};

export function getEndpointBySlug(slug: string): ApiEndpoint | undefined {
  const resolved = API_SLUG_ALIASES[slug] || slug;
  for (const group of apiGroups) {
    const endpoint = group.endpoints.find((e) => e.id === resolved);
    if (endpoint) return endpoint;
  }
  return undefined;
}

export function getGroupForEndpoint(endpointId: string): ApiGroup | undefined {
  return apiGroups.find((group) =>
    group.endpoints.some((e) => e.id === endpointId)
  );
}

export function generateApiTableOfContents(endpointId: string) {
  const endpoint = getEndpointBySlug(endpointId);
  if (!endpoint) return [];

  const items: { id: string; title: string; level: "h2" | "h3" }[] = [
    { id: "endpoint", title: "Endpoint", level: "h2" },
  ];

  if (endpoint.headers && endpoint.headers.length > 0) {
    items.push({ id: "headers", title: "Headers", level: "h2" });
  }

  if (endpoint.requestBody && endpoint.requestBody.length > 0) {
    items.push({ id: "request-body", title: "Request Body", level: "h2" });
  }

  items.push({ id: "response", title: "Response", level: "h2" });

  if (endpoint.exampleRequest || endpoint.exampleResponse) {
    items.push({ id: "example-usage", title: "Example Usage", level: "h2" });
  }

  return items;
}
